display_name: NonebotGUI
package_name: NonebotGUI
maintainer:
  name: 【夜风】NightWind
  email: HT30332@126.com
co_authors:
  - name: 【夜风】NightWind
    email: HT30332@126.com
priority: optional
section: x11
installed_size: 6604
essential: false
icon: asset/icon/icon.png

postinstall_scripts: []
postuninstall_scripts:
  - 'echo 感谢您的使用，再见！'

keywords:
  - Nonebot

generic_name: NonebotGUI

categories:
  - Utility

startup_notify: true
